DM-42080: Add effTime to computeExposureSummaryStats
lsst/obs_subaru pull request #466
Opened 2024-01-27 16:18 UTC by kadrlica

2024-01-30 18:20 UTC, erykoff requested changes

2024-01-30 18:20 UTC, erykoff commented on config/updateVisitSummary.py
> +print("-----DEBUG: config/updateVisitSummary.py-----")
Please remove debug statement.  Thanks!

2024-01-30 20:23 UTC, kadrlica commented on config/updateVisitSummary.py
> +print("-----DEBUG: config/updateVisitSummary.py-----")
Oops! Should be fixed.

2024-01-31 19:41 UTC, erykoff approved these changes

2024-01-31 21:42 UTC, merged